name: chat_with_me
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.3
  animated_text_kit: ^1.3.1
  firebase_core: ^0.4.3+1
  firebase_auth: ^0.15.3
  cloud_firestore: ^0.13.0+1
  modal_progress_hud: ^0.1.3




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/logo.png"


flutter:

  uses-material-design: true

  
  assets:
   - assets/images/icons/logo.png
   - assets/images/icons/flash.png
